### ISSUE TITLE
How i'm test

### ISSUE THREAD

**Issue by gkpiccoli** [MasterAwesome/android_device_xiaomi_laurel_sprout#2]
Hi, how i test the ROM? I try to install via TWRP but an error encountered in the zip file. I'm using MIUI version of bitnet. Sorry for  my ignorance or stupidity. Save from Brazil!

**Comment by ashu00** [comment]
> Hi, how i test the ROM? I try to install via TWRP but an error encountered in the zip file. I'm using MIUI version of bitnet. Sorry for my ignorance or stupidity. Save from Brazil!

This rom requires stock android 11 FW, and there's currently no twrp working for android 11.

Look here for install instructions: 
https://forum.xda-developers.com/t/ota-lineage-18-1-unofficial-laurel_sprout-mi-a3-15-05-2021.4227347/

**Comment by MasterAwesome** [comment]
Check the telegram group at https://t.me/lineage_laurel_sprout
